spring.application.name=dobebets-api
spring.datasource.url=jdbc:postgresql://localhost:5432/betting_prediction_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# API-Football settings. Read the secret key from the environment.
api-football.base-url=https://v3.football.api-sports.io
api-football.api-key=${API_KEY}

spring.security.User.name=tipster
spring.security.User.password=${TIPSTER_PASSWORD}